# Generated by Django 5.1.1 on 2024-10-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='estoque',
        ),
    ]
