# Generated by Django 5.1.1 on 2024-10-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_remove_produtos_codigo_remove_produtos_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=255)),
                ('departament', models.CharField(max_length=255)),
            ],
        ),
    ]
