# Generated by Django 5.1.1 on 2024-10-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='departament',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='react',
            name='employee',
            field=models.CharField(max_length=30),
        ),
    ]
